apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::158433753848:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::158433753848:role/eksctl-eksctl-demo-nodegroup-ng-c-NodeInstanceRole-W0AR80YASLSH
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-15T09:06:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1913"
  uid: 4a005d4c-f90f-4b7d-9c76-279881ee6133
